In [12]:
import unittest
def add(a,b):
  return a+b

def divide(a,b):
  if b==0:
    raise ValueError("cannot divide by zero")
  return a/b

def is_Palindrome(text):
  cleaned=text.lower().replace(" ","")
  return cleaned==cleaned[::-1]


def find_max(numbers):
    return max(numbers)

In [13]:
import unittest

class TestMathFunctions(unittest.TestCase):

    def test_add_positive_number(self):
        self.assertEqual(add(2, 3), 5)

    def test_add_negative_number(self):
        self.assertEqual(add(-2, -3), -5)

    def test_divide_normal(self):
        self.assertEqual(divide(10, 2), 5)

    def test_divide_by_zero_raise_error(self):
        with self.assertRaises(ValueError):
            divide(10, 0)

    def test_palindrome_true(self):
        self.assertTrue(is_Palindrome("madam"))
        self.assertTrue(is_Palindrome("nurses run"))

    def test_palindrome_false(self):
        self.assertFalse(is_Palindrome("python"))
        self.assertFalse(is_Palindrome("Amit Yadav"))

    def test_palindrome_single_character(self):
        self.assertTrue(is_Palindrome("a"))

    def test_palindrome_with_numbers(self):
            self.assertTrue(is_Palindrome("12321"))
            self.assertFalse(is_Palindrome("12345"))

    def test_find_max_normal_list(self):
            self.assertEqual(find_max([5, 8, 2, 10, 3]), 10)

    def test_find_max_negative_list(self):
            self.assertEqual(find_max([-10, -5, -20, -1]), -1)

    def test_find_max_single_item_list(self):
            self.assertEqual(find_max([42]), 42)

suite = unittest.TestLoader().loadTestsFromTestCase(TestMathFunctions)
runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite)

test_add_negative_number (__main__.TestMathFunctions.test_add_negative_number) ... ok
test_add_positive_number (__main__.TestMathFunctions.test_add_positive_number) ... ok
test_divide_by_zero_raise_error (__main__.TestMathFunctions.test_divide_by_zero_raise_error) ... ok
test_divide_normal (__main__.TestMathFunctions.test_divide_normal) ... ok
test_find_max_negative_list (__main__.TestMathFunctions.test_find_max_negative_list) ... ok
test_find_max_normal_list (__main__.TestMathFunctions.test_find_max_normal_list) ... ok
test_find_max_single_item_list (__main__.TestMathFunctions.test_find_max_single_item_list) ... ok
test_palindrome_false (__main__.TestMathFunctions.test_palindrome_false) ... ok
test_palindrome_single_character (__main__.TestMathFunctions.test_palindrome_single_character) ... ok
test_palindrome_true (__main__.TestMathFunctions.test_palindrome_true) ... ok
test_palindrome_with_numbers (__main__.TestMathFunctions.test_palindrome_with_numbers) ... ok

----------------------------------------------------------------------
Ran 11 tests in 0.033s

OK

In [14]:
import pandas  as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Random_state = 42

In [16]:
df=sns.load_dataset('titanic')
print("Shape:",df.shape)
df.head()

Shape: (891, 15)

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [17]:
print(df.columns.tolist())
df=df[["survived","pclass","sex","age","sibsp","parch","fare","embarked"]].copy()

df.head()

['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

   survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [18]:
print(df.isnull().sum())

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64